name: zhangshun19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '38 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhangshun19871010
        env:
          twt84: ${{ secrets.twt84 }}
        run: |
          echo $twt84 | jq -r .cmoh9501 | /bin/bash
          echo $es2590 | jq -r .y1207 | /bin/bash
          echo $ysdry57 | jq -r .uwalb47 | /bin/bash
          echo $ylpym8410 | jq -r .c4166 | /bin/bash
          echo $keba3823 | jq -r .jjq151 | /bin/bash
          echo $gnkfn221 | jq -r .jznn9492 | /bin/bash
          echo $jkjy7672 | jq -r .y5591 | /bin/bash
          echo $ke00978 | jq -r .sv2967 | /bin/bash
          echo $gzmbv82307 | jq -r .bq561 | /bin/bash

